#ifndef GLDMASKBOX_GLOBAL_H
#define GLDMASKBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLDMASKBOX_LIBRARY)
#  define GLDMASKBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GLDMASKBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLDMASKBOX_GLOBAL_H
