#ifndef GLDSTRINGS_H
#define GLDSTRINGS_H

#include "GLDString.h"
#include "GLDResourceDef.h"
#include "GLDGlobal.h"

DEF_RESOURCESTRING5(g_InvalidInteger);
DEF_RESOURCESTRING5(g_InvalidFloat);
DEF_RESOURCESTRING5(g_InvalidGUID);
DEF_RESOURCESTRING5(g_InvalidTypeCompare);

DEF_RESOURCESTRING5(g_sInvalidBase64Data);
DEF_RESOURCESTRING5(g_rsInvalidTimeFormat);

DEF_RESOURCESTRING5(g_MissingExtPropCode);
DEF_RESOURCESTRING5(g_ExtPropCodeExist);

DEF_RESOURCESTRING5(g_InvalidFieldName);
DEF_RESOURCESTRING5(g_NeedRunState);
DEF_RESOURCESTRING5(g_InvalidFieldNameMark);
DEF_RESOURCESTRING5(g_NotExistVisibleCol);

DEF_RESOURCESTRING5(g_InvalidXMLNode);
DEF_RESOURCESTRING5(g_NeedXMLNode);

DEF_RESOURCESTRING5(g_InvalidBinFile);
DEF_RESOURCESTRING5(g_ReadBinFileError);

DEF_RESOURCESTRING5(g_SelectImage);
DEF_RESOURCESTRING5(g_SquareReplace);
DEF_RESOURCESTRING5(g_CubeReplace);

DEF_RESOURCESTRING5(g_rsInvalideRule);
DEF_RESOURCESTRING5(g_rsHasNoActiveSheet);
DEF_RESOURCESTRING5(g_rsGetMergeRectFailed);
DEF_RESOURCESTRING5(g_rsTitleIndex);
DEF_RESOURCESTRING5(g_rsTitleSelect);
DEF_RESOURCESTRING5(g_rsTitleSymbol);

DEF_RESOURCESTRING5(g_rsMonth);
DEF_RESOURCESTRING5(g_rsYear);
DEF_RESOURCESTRING5(g_rsDay);
DEF_RESOURCESTRING5(g_rsMonDay);
DEF_RESOURCESTRING5(g_rsTueDay);
DEF_RESOURCESTRING5(g_rsWedDay);
DEF_RESOURCESTRING5(g_rsThuDay);
DEF_RESOURCESTRING5(g_rsFriDay);
DEF_RESOURCESTRING5(g_rsSatDay);
DEF_RESOURCESTRING5(g_rsSunDay);

DEF_RESOURCESTRING5(g_rsFontEffect);
DEF_RESOURCESTRING5(g_rsEffect);
DEF_RESOURCESTRING5(g_rsNoLine);
DEF_RESOURCESTRING5(g_rsOtherLine);
DEF_RESOURCESTRING5(g_rsLineWidth);

DEF_RESOURCESTRING5(g_rsAutoHide);
DEF_RESOURCESTRING5(g_rsLocked);

DEF_RESOURCESTRING5(g_rsSimsun);
DEF_RESOURCESTRING5(g_rsAccount);
DEF_RESOURCESTRING5(g_rsPassword);
DEF_RESOURCESTRING5(g_rsLogin);
DEF_RESOURCESTRING5(g_rsCancel);
DEF_RESOURCESTRING5(g_rsRegisterAccount);
DEF_RESOURCESTRING5(g_rsGetBackPassword);
DEF_RESOURCESTRING5(g_rsRemeberPassword);
DEF_RESOURCESTRING5(g_rsAutoLogin);
DEF_RESOURCESTRING5(g_rsOpenVirtualKeyboard);
DEF_RESOURCESTRING5(g_rsAccountError);
DEF_RESOURCESTRING5(g_rsLoginError);
DEF_RESOURCESTRING5(g_rsNetworkError);

GLDCOMMONSHARED_EXPORT GString getGLDi18nStr(const char *originalStr);
GLDCOMMONSHARED_EXPORT GString getGSPi18nStr(const char *originalStr);
GLDCOMMONSHARED_EXPORT GString getGEPEnginei18nStr(const char *originalStr);

#endif // GLDSTRINGS_H
