#ifndef GLDTABLEVIEW_GLOBAL_H
#define GLDTABLEVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef GLD_FULLSOURCE
    #if defined(GLDTABLEVIEW_LIBRARY)
    #  define GLDTABLEVIEWSHARED_EXPORT Q_DECL_EXPORT
    #else
    #  define GLDTABLEVIEWSHARED_EXPORT Q_DECL_IMPORT
    #endif
#else
    #define GLDTABLEVIEWSHARED_EXPORT
#endif

#endif // GLDTABLEVIEW_GLOBAL_H
